package com.ipsakti.ip_sakti_backend.formulation.model;

public enum DocumentStatus {
    DOCUMENT_PROVIDED,
    DOCUMENT_VERIFIED_AGAINST_AUTHORITATIVE_SOURCE,
    DOCUMENT_NOT_VERIFIED,
    DOCUMENT_MISSING,
    DOCUMENT_NOT_APPLICABLE,
    DOCUMENT_REQUIRES_HUMAN_AUTHORITY_VERIFICATION
}
