package com.ipsakti.ip_sakti_backend.formulation.model;

public enum DocumentType {
    FORMULATION_SPECIFICATION,
    INGREDIENT_LIST,
    INGREDIENT_SOURCE_RECORDS,
    MANUFACTURER_CERTIFICATE,
    MANUFACTURING_INFO,
    PRODUCT_LABEL,
    PACKAGING_INFO,
    QUALITY_TEST_REPORT,
    STABILITY_STUDY,
    CLASSICAL_TEXT_REFERENCE,
    TRADITIONAL_USE_EVIDENCE,
    PATENT_DOCUMENT,
    TRADEMARK_INFO,
    GI_INFO,
    BIODIVERSITY_RESOURCE_INFO,
    NBA_ABS_APPROVAL,
    AYUSH_DRUG_LICENSE,
    FSSAI_LICENSE,
    OTHER
}
