package com.ipsakti.ip_sakti_backend.tk.model;

public enum TkOverlapType {
    INGREDIENT_OVERLAP,
    TRADITIONAL_USE_OVERLAP,
    FORMULATION_OVERLAP,
    PREPARATION_METHOD_OVERLAP,
    PROCESS_OVERLAP,
    KNOWLEDGE_DOMAIN_OVERLAP,
    GEOGRAPHIC_OR_COMMUNITY_OVERLAP,
    BIOLOGICAL_RESOURCE_OVERLAP
}
